CREATE TABLE `main_registrations` (
 `rg_registrationID` INT(10) UNSIGNED NOT NULL,
 `rg_eventID` INT(10) UNSIGNED NULL,
 `rg_firstname` VARCHAR(20) NOT NULL COLLATE 'utf8_general_ci',
 `rg_lastname` VARCHAR(20) NOT NULL COLLATE 'utf8_general_ci',
 `rg_gender` CHAR(1) NULL COLLATE 'utf8_general_ci',
 `rg_birthyear` SMALLINT(5) UNSIGNED NULL,
 `rg_birthmonth` TINYINT(3) UNSIGNED NULL,
 `rg_birthday` TINYINT(3) UNSIGNED NULL COMMENT 'Only the day of the month',
 `rg_is_under18` TINYINT(3) UNSIGNED NOT NULL,
 `rg_addr` VARCHAR(150) NULL COLLATE 'utf8_general_ci',
 `rg_zip` VARCHAR(10) NULL COLLATE 'utf8_general_ci',
 `rg_city` VARCHAR(50) NULL COLLATE 'utf8_general_ci',
 `rg_state` VARCHAR(20) NULL COLLATE 'utf8_general_ci',
 `rg_country` VARCHAR(2) NULL COLLATE 'utf8_general_ci',
 `rg_phone` VARCHAR(20) NULL COLLATE 'utf8_general_ci',
 `rg_email` VARCHAR(100) NULL COLLATE 'utf8_general_ci',
 `rg_group_with` INT(10) UNSIGNED NULL,
 `rg_from_date` DATE NULL,
 `rg_to_date` DATE NULL,
 `rg_discount_code` VARCHAR(15) NULL COLLATE 'utf8_general_ci',
 `rg_amount_to_pay` DECIMAL(10,2) UNSIGNED NOT NULL,
 `rg_amount_received` DECIMAL(10,2) UNSIGNED NULL,
 `rg_payment_receivedby` VARCHAR(30) NULL COLLATE 'utf8_general_ci',
 `rg_payment_date` DATETIME NULL,
 `rg_payment_method` VARCHAR(15) NULL COLLATE 'utf8_general_ci',
 `rg_payment_reference` VARCHAR(60) NULL COLLATE 'utf8_general_ci',
 `rg_invoice_no` INT(10) UNSIGNED NULL,
 `rg_payment_comments` MEDIUMTEXT NULL COLLATE 'utf8_general_ci',
 `rg_parental_letter_received` DATE NULL,
 `rg_customfield1` VARCHAR(5000) NULL COLLATE 'utf8_general_ci',
 `rg_customfield2` VARCHAR(5000) NULL COLLATE 'utf8_general_ci',
 `rg_customfield3` VARCHAR(5000) NULL COLLATE 'utf8_general_ci',
 `rg_customfield4` VARCHAR(5000) NULL COLLATE 'utf8_general_ci',
 `rg_customfield5` TEXT NULL COLLATE 'utf8_general_ci',
 `rg_customfield6` TEXT NULL COLLATE 'utf8_general_ci',
 `rg_customfield7` TEXT NULL COLLATE 'utf8_general_ci',
 `rg_customfield8` TEXT NULL COLLATE 'utf8_general_ci',
 `rg_customfield9` TEXT NULL COLLATE 'utf8_general_ci',
 `rg_customfield10` TEXT NULL COLLATE 'utf8_general_ci',
 `rg_customfield11` MEDIUMTEXT NULL COLLATE 'utf8_general_ci',
 `rg_customfield12` MEDIUMTEXT NULL COLLATE 'utf8_general_ci',
 `rg_customfield13` MEDIUMTEXT NULL COLLATE 'utf8_general_ci',
 `rg_customfield14` MEDIUMTEXT NULL COLLATE 'utf8_general_ci',
 `rg_customfield15` MEDIUMTEXT NULL COLLATE 'utf8_general_ci',
 `rg_customfield16` MEDIUMTEXT NULL COLLATE 'utf8_general_ci',
 `rg_customfield17` MEDIUMTEXT NULL COLLATE 'utf8_general_ci',
 `rg_customfield18` MEDIUMTEXT NULL COLLATE 'utf8_general_ci',
 `rg_customfield19` MEDIUMTEXT NULL COLLATE 'utf8_general_ci',
 `rg_customfield20` MEDIUMTEXT NULL COLLATE 'utf8_general_ci',
 `rg_customfield21` MEDIUMTEXT NULL COLLATE 'utf8_general_ci',
 `rg_customfield22` MEDIUMTEXT NULL COLLATE 'utf8_general_ci',
 `rg_customfield23` MEDIUMTEXT NULL COLLATE 'utf8_general_ci',
 `rg_customfield24` MEDIUMTEXT NULL COLLATE 'utf8_general_ci',
 `rg_customfield25` MEDIUMTEXT NULL COLLATE 'utf8_general_ci',
 `rg_customfield26` MEDIUMTEXT NULL COLLATE 'utf8_general_ci',
 `rg_customfield27` MEDIUMTEXT NULL COLLATE 'utf8_general_ci',
 `rg_customfield28` MEDIUMTEXT NULL COLLATE 'utf8_general_ci',
 `rg_customfield29` MEDIUMTEXT NULL COLLATE 'utf8_general_ci',
 `rg_customfield30` MEDIUMTEXT NULL COLLATE 'utf8_general_ci',
 `rg_comments` MEDIUMTEXT NULL COLLATE 'utf8_general_ci',
 `rg_arrival_comments` MEDIUMTEXT NULL COLLATE 'utf8_general_ci',
 `rg_assigned_roomID` VARCHAR(15) NULL COLLATE 'utf8_general_ci',
 `rg_pincode` SMALLINT(5) UNSIGNED NULL,
 `rg_on_waiting_list` TINYINT(3) UNSIGNED NOT NULL,
 `rg_user_lang` CHAR(2) NULL COLLATE 'utf8_general_ci',
 `rg_date_added` DATETIME NOT NULL,
 `rg_date_activated` DATETIME NULL,
 `rg_date_arrived` DATETIME NULL,
 `rg_arrived_by` VARCHAR(30) NULL COLLATE 'utf8_general_ci',
 `rg_date_cancelled` DATETIME NULL
);

CREATE TABLE `printqueue` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `ip` varchar(20) DEFAULT NULL,
  `printerid` tinyint(4) unsigned DEFAULT NULL,
  `printed` tinyint(4) unsigned DEFAULT '0',
  `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `file` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5837 DEFAULT CHARSET=utf8;

CREATE TABLE `rooms` (
  `id` varchar(11) NOT NULL DEFAULT '',
  `gender` varchar(8) DEFAULT NULL,
  `label` varchar(20) DEFAULT 'Teilnehmer',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
